# Generated by Django 3.1.4 on 2021-01-11 17:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='slug',
            field=models.SlugField(default=django.utils.timezone.now, max_length=100, unique=True, verbose_name='Identificador'),
            preserve_default=False,
        ),
    ]
