# Generated by Django 3.1.4 on 2021-01-10 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_auto_20210107_1839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-number'], 'verbose_name': 'Aula', 'verbose_name_plural': 'Aulas'},
        ),
    ]
